### ISSUE TITLE
Move Board of Directors onto About Us page

### ISSUE THREAD

**Issue by singleportrait** [JustFixNYC/website#6]
- Move directors over to Our Team page
- Change Board of Directors styles
- Update Our Team section to accommodate more members
- Add "Read more" functionality to the bios
- Test mobile
- Remove Board of Directors page
- Question: Remove Sateesh Nori?
- Question: Set up a 301 for that URL?

**Comment by atreni** [comment]
can we put a space after [... Read More]

**Comment by singleportrait** [comment]
Closed by pull #15.
